Additional Waiting List Tests
thewca/worldcubeassociation.org pull request #10241
Opened 2024-11-12 18:46 UTC by dunkOnIT

## Questions:
- [ ] What behaviour do we want if a payload is received that contains a waiting list position, but the registration isn't on the waiting list yet? 
  - [ ] Reject it in the checker?
  - [ ] Add it to the waiting list at the end?
  - [ ] Add it to the waiting list in the given position?

2024-11-12 21:03 UTC, FinnIckler commented
I think those questions are part of a larger API modelling discussion

2024-11-13 10:00 UTC, gregorbg commented
In my opinion there's only really two options here:
1. Reject the competition because of the waiting list part of the payload explicitly
2. Drop/ignore the waiting list part of the payload implicitly

2024-11-13 10:02 UTC, gregorbg commented
If a competition is not on the waiting list -- and, crucially, if the update payload does **not** specify that it wants to be put on the waiting list -- then there should be no additional information about waiting list positions.

As Finn said, this then only boils down to a general decision about "complain loudly" (and thereby implicitly don't process the waiting list part) or "ignore quietly" (and thereby implicitly don't process the waiting list part).

Adding the user in any capacity or any position to the waiting list when the same update payload does not explicitly specify "please put me to status `waiting_list`" gets a big no-no from me.

2024-11-13 13:23 UTC, dunkOnIT commented
I'm partial to loudly shouting "hey, this registration isn't on the waiting list", which would be 2 tests: 
1. Throw an error in the registration_checker if we get a waiting list position but no competing_status: waiting_list
1. Throw an error in the `waiting_list.rb` model if we call `add` on a Registration without a `waiting_list` competing_status

2024-11-15 08:23 UTC, gregorbg commented
> I'm partial to loudly shouting "hey, this registration isn't on the waiting list", which would be 2 tests:

Okay!

> This leads to a second question: What if we get a payload which contains a `waiting_list` competing_status AND a waiting_list_position? Do we
> 
> * add it to the waiting list at the given position? Or,
> * reject it because adding and moving to different positions should be done in separate steps?

Please go with `add it to the waiting list at the given position`. The rationale here should be that the payload itself _should_ support this in the backend. If we have strong opinions about what users of our website are(n't) allowed to do, then we should block these actions in the frontend.

2024-11-18 03:55 UTC, dunkOnIT commented
> If we have strong opinions about what users of our website are(n't) allowed to do, then we should block these actions in the frontend.

My only concern with this is that we also at some point want this API to be accessible by third parties - so if there's an action we don't want to support, it also needs to be enforced at the API level (at least in my view)

2025-01-04 11:32 UTC, gregorbg commented
Just curious, what is the status on this? (Especially seeing that we discussed about waiting list issues for over one hour yesterday)

2025-01-27 12:30 UTC, dunkOnIT commented
Busy finalizing this. A few design decisions I'm making: 
- **Passing waiting_list the `registration` object instead of an `entry_id`:** 
  -  I've added a check in the `waiting_list.add` method that the registration's status must be waiting_list - however, when we call `waiting_list.add` the registration object hasn't yet been saved
  - Another option here would be to finish updating the registration before adding it to the waiting list - problem with this is that we're determining the changes for the history entry during the db transaction - and we'd like to include the waiting list position in the history (which we can only do if the reg has been added to the waiting list)
  - This also saves us a database call by using the in-memory object instead of looking up the reg again in `waiting_list.add`
  - I've changed this for the `remove` and `move` functions as well, just for the sake of consistency

TODO: 
- [ ] Add a validation that a reg must have a `waiting_list_position` in order to be saved with the `waiting_list` status
- [ ] Add waiting list position to the `changes` hash passed to `add_history_entry`

2025-01-30 08:37 UTC, dunkOnIT commented
Ready for review

2025-02-12 04:38 UTC, gregorbg requested changes

2025-02-12 04:38 UTC, gregorbg commented on app/models/waiting_list.rb
I have to veto this in its current state. Passing the whole registration specifically and assuming knowledge about its properties defeats the whole idea of having WaitingList be generic.
You could either:
- Perform the `registration.competing_status == Registrations::Helper::STATUS_WAITING_LIST` check outside of this model, immediately before the `add` method is being called
- Or add a `can_be_waitlisted?` method (or similar) to each and every model that should support waitlisting (kinda like an `interface` definition except Ruby doesn't support interfaces)

2025-02-12 04:38 UTC, gregorbg commented on app/models/waiting_list.rb
To be clear, I'm not at all against passing in the whole entity, I just don't want this class to make any assumptions about what kind of entity it is.

2025-02-12 04:38 UTC, gregorbg commented on app/models/waiting_list.rb
But then again, as far as I can tell, if you skip that one `raise` check that I'm complaining about then suddenly all the code ever needs is the ID of the entity so passing the whole entity becomes redundant again.

2025-02-12 04:38 UTC, gregorbg commented on app/models/waiting_list.rb
I'll leave the details and choice up to you, the only thing I am adamant about is not having registration-specific business logic inside this generic (polymorphic-capable) `WaitingList` class.

2025-02-13 11:59 UTC, dunkOnIT commented on app/models/waiting_list.rb
I'm preferring the `can_be_waitlisted?` solution, because there's no restriction on where in the code `waiting_list.add()` could be called from - even though at the moment we only use it in `lanes/competing.rb` - and so I prefer being able to enforce restrictions about what can be added to the waiting list from one central place.

2025-02-14 04:56 UTC, gregorbg requested changes

2025-02-14 04:56 UTC, gregorbg commented on spec/requests/api_registrations_spec.rb
> +      waitlisted3 = FactoryBot.create(:registration, competition: competition)
These don't have the `:waiting_list` trait, but I feel like they should? (Based on the fact that in the previous state of things, you had added them to the waiting list manually)

2025-02-14 04:56 UTC, gregorbg commented on app/models/waiting_list.rb
Why not just rename from `entry_id` to `entry`?

2025-02-14 04:56 UTC, gregorbg commented on app/models/waiting_list.rb
Cool!

2025-02-14 04:56 UTC, gregorbg commented on app/models/waiting_list.rb
> +    item.can_be_waitlisted! # can_be_waitlisted! raises an error if it fails
Ruby trick: You can do `item.try(:can_be_waitlisted!)` which (obviously) _tries_ to call it if the method is defined, but doesn't explode if you forget to implement it.

2025-02-14 04:56 UTC, gregorbg commented on app/models/registration.rb
> +  def can_be_waitlisted!
Not too wild about the `can_be_` and `!` combination. I know that the usage of `!` is a bit overloaded between "throws an error" and "mutates in-place", but perhaps something like `check_waitlist!`-ish can do?

2025-02-14 05:25 UTC, dunkOnIT commented on app/models/waiting_list.rb
Good point!

2025-02-14 05:32 UTC, dunkOnIT commented on spec/requests/api_registrations_spec.rb
> +      waitlisted3 = FactoryBot.create(:registration, competition: competition)
Great catch - I've added assertions to check their status before the test runs as well

2025-02-14 05:35 UTC, dunkOnIT commented on app/models/waiting_list.rb
> +    item.can_be_waitlisted! # can_be_waitlisted! raises an error if it fails
Implemented

2025-02-14 05:36 UTC, dunkOnIT commented on app/models/registration.rb
> +  def can_be_waitlisted!
Gone with `ensure_waitlist_eligibility!` which feels like it avoids sounding like a boolean check while keeping the method purpose clear

2025-02-27 08:34 UTC, gregorbg requested changes

2025-02-27 08:34 UTC, gregorbg commented on spec/models/registration_spec.rb
> +        expect(reg4.reload.waiting_list_position).to eq(nil)
Curious: Why is a `reload` necessary here when it wasn't necessary before?

2025-02-27 08:34 UTC, gregorbg commented on spec/models/registration_spec.rb
> -
Why did this poor blank line have to die? :sob:

2025-03-03 04:08 UTC, dunkOnIT commented on spec/models/registration_spec.rb
> -
I eat blank lines for breakfast (fixed)

2025-03-03 04:08 UTC, dunkOnIT commented on spec/models/registration_spec.rb
> +        expect(reg4.reload.waiting_list_position).to eq(nil)
Apparently is isn't? Fixed

2025-03-03 04:08 UTC, dunkOnIT commented on spec/models/registration_spec.rb
> +        expect(reg4.reload.waiting_list_position).to eq(nil)
Speculation: LIkely added the reload in an attempt to fix the test which was failing for an unrelated reason, and forgot to remove it once the test was passing again

2025-03-03 04:27 UTC, gregorbg approved these changes

2025-03-03 05:08 UTC, merged