Add support for newcomer month
thewca/worldcubeassociation.org pull request #10328
Opened 2024-11-26 09:48 UTC by dunkOnIT

Questions:
- Do we want some kind of validation on when to allow newcomer spots to be reserved? I see 2 options:
  1. [what I'm currently doing] 
  2. Setting NEWCOMER_MONTH_START/END_DATE and checking if the comp's {start date/end date?} falls inside that range

2024-12-12 09:41 UTC, dunkOnIT commented on app/webpacker/components/CompetitionForm/FormSections/CompetitorLimit.js
> +        <InputNumber id="newcomerReservedSpots" min={0} />
Calculate and display the max number of newcomer reserved spots allowed per the 50% WCRP exception limit

2025-01-03 11:45 UTC, gregorbg requested changes

2025-01-03 11:45 UTC, gregorbg commented on app/models/competition.rb
> +  NEWCOMER_MONTH_ENABLED = true
Do we really need to hard-code this? We could just leave the form field as `enabled` all the time and have WCAT manually verify.

At least until we come up with a smarter solution of "marking" newcomer month start and end dates in the DB

2025-01-03 11:45 UTC, gregorbg commented on app/models/competition.rb
> +    registrations.competing_status_accepted.includes(:user).select { |registration| registration.user.newcomer? }
Now that we're fully committed to V3, this can be `registrations.accepted...`

2025-01-03 11:45 UTC, gregorbg commented on app/models/competition.rb
> +    registrations.competing_status_accepted.includes(:user).select { |registration| registration.user.newcomer? }
Regarding optimization: That depends on what you're trying to achieve.
- If you really want to get the whole list of users, to access their properties (name, dob, email, whatever) or display them in a frontend _fully_, then this is as optimized as it can get
- If the only purpose of this method is to obtain a _count_ of newcomers, then you effectively discard all of the "hard work" of optimizing and preloading. A more effective way would need a `newcomer` **scope** on `User` to then do something along the lines of `registrations.accepted.joins(:user).merge(User.newcomer).count`

2025-01-03 11:45 UTC, gregorbg commented on spec/factories/competitions.rb
> +    # TODO: This should change to :v3
I think it has already if you merge in `main` now :wink:

2025-01-03 13:35 UTC, dunkOnIT commented
I've had to disable a CyclomaticComplexity warning on `validate_update_status` - I think `validate_update_status` is due for a refactor, and #10519 will track doing that - but it is beyond the scope of this PR.

2025-01-03 13:35 UTC, dunkOnIT commented on app/models/competition.rb
> +    registrations.competing_status_accepted.includes(:user).select { |registration| registration.user.newcomer? }
Updated!

2025-01-13 09:15 UTC, dunkOnIT commented
@gregorbg tests passing, ready for review

2025-02-20 10:18 UTC, gregorbg requested changes

2025-02-20 10:18 UTC, gregorbg commented on db/migrate/20241126084446_add_newcomer_reserved_spots_to_competitions.rb
> +    add_column :Competitions, :newcomer_reserved_spots, :integer, default: 0, null: false
You could use `null` here as a way of saying "I don't want to specify such a limit".
Although admittedly, `0` serves the same effect, so I have only a slight bias towards an actual `null` column

2025-02-20 10:18 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +          if !target_user.newcomer? && competition.newcomer_reserved_spots > 0
In line with my other comment above, this check would make slightly more sense if you use `null` instead of a zero value.

2025-02-20 10:18 UTC, gregorbg commented on app/webpacker/components/CompetitionForm/FormSections/CompetitorLimit.js
> +        <InputNumber id="newcomerReservedSpots" min={0} />
Is this comment a mental TODO?

2025-02-20 10:18 UTC, gregorbg commented on app/models/user.rb
> +  end
This is a little bit ambiguous definition of the term "Newcomer".
In the intuitive sense, a newcomer only denotes a person who has never competed before. The second part after the `||` is specific to WCA Newcomer Month. Can we rename the method or maybe split it in two?

2025-02-20 10:18 UTC, gregorbg commented on app/models/user.rb
> +  scope :newcomers, -> { where(wca_id: nil).or(where('wca_id LIKE ?', "#{Time.current.year}%")) }
Same as my other remark below about the definition "Newcomer".

2025-02-20 10:18 UTC, gregorbg commented on app/models/competition.rb
> +    max_newcomer_spots = (competitor_limit * MAX_NEWCOMER_SPOTS_RESERVED_FRACTION).to_i
Do the rules of Newcomer Month (or WCRP or whatnot) somehow indicate whether this should be rounded up or down?
In any case, I think it would be good to make that explicit by using either `floor` or `ceil` (or perhaps even `round` FWIW)

2025-02-20 10:18 UTC, gregorbg commented on app/models/competition.rb
> +  NEWCOMER_MONTH_ENABLED = true
You marked this conversation as resolved but the constant is still there. It is completely unused as far as I can tell.

2025-02-20 13:22 UTC, dunkOnIT commented on lib/registrations/registration_checker.rb
> +          if !target_user.newcomer? && competition.newcomer_reserved_spots > 0
See comment above

2025-02-20 13:25 UTC, dunkOnIT commented on app/webpacker/components/CompetitionForm/FormSections/CompetitorLimit.js
> +        <InputNumber id="newcomerReservedSpots" min={0} />
I honestly have no idea - it seems like a nice idea, but newcomer month is soon enough that I'd say let's just get this out the door and worry about QOL if another newcomer month ever comes around

2025-02-20 13:32 UTC, dunkOnIT commented on app/models/competition.rb
> +    max_newcomer_spots = (competitor_limit * MAX_NEWCOMER_SPOTS_RESERVED_FRACTION).to_i
It doesn't - I've set it to `floor`, on the assumptions that (a) it doesn't matter, and (b) if it did, we'd rather have 1 more flexible spot than 1 specifically reserved for newcomers - given that the newcomer reservation portion is already very generous

2025-02-20 13:40 UTC, dunkOnIT commented on app/models/competition.rb
> +    return unless competitor_limit.present?
Done

2025-02-21 04:09 UTC, gregorbg requested changes

2025-02-21 04:09 UTC, gregorbg commented on app/models/user.rb
> +  end
Rather than a comment, you should rename this method. If the name is `newcomer?` then there is **definitely** a strong intuitional bias towards "has never competed before".

The first thing that comes to mind is `newcomer_month_eligible?`

2025-02-21 04:09 UTC, gregorbg commented on app/webpacker/components/CompetitionForm/FormSections/CompetitorLimit.js
> +        <InputNumber id="newcomerReservedSpots" min={0} />
Okidoki

2025-02-21 04:09 UTC, gregorbg commented on db/migrate/20241126084446_add_newcomer_reserved_spots_to_competitions.rb
> +    add_column :Competitions, :newcomer_reserved_spots, :integer, default: 0, null: false
The other PR will probably be merged first :wink:

2025-02-21 04:09 UTC, gregorbg commented on spec/models/user_spec.rb
> +  describe 'newcomer?' do
Relevant if we rename the method.

2025-02-21 04:09 UTC, gregorbg commented on spec/factories/registrations.rb
> +    trait :first_timer do
I like this as a term, but I would use it the other way around!
As in, `newcomer` is someone who really has absolutely zero competition experience, while `first_timer` is someone who competed for the first time this year.

But I'm happy to defer to consensus and a broader vote

2025-02-25 13:43 UTC, gregorbg commented on app/models/competition.rb
> +  MAX_NEWCOMER_SPOTS_RESERVED_FRACTION = 0.5
Basically, we should also change this to `MAX_NEWCOMER_MONTH_SPOTS_RESERVED_FRACTION`, but that becomes unfortunately long. Any ideas for a shorter name?

2025-02-25 13:44 UTC, gregorbg commented on app/models/user.rb
> +  scope :newcomer_month_eligible, -> { where(wca_id: nil).or(where('wca_id LIKE ?', "#{Time.current.year}%")) }
You can actually define this as `-> { newcomers.or(...) }`

2025-02-25 13:48 UTC, gregorbg commented on app/models/competition.rb
> +  end
Can you move these into functions under `registration.rb` similar to the already existing `def accepted_count` and `def accepted_and_paid_pending_count`?

2025-02-25 13:48 UTC, gregorbg commented on app/models/competition.rb
> +  end
In the latter case of `newcomer_month_reserved_spots_remaining`, it will suffice to only move the count itself into `registration.rb` and leave the subtraction here

2025-02-25 13:51 UTC, gregorbg commented on app/models/user.rb
> +  def newcomer?
Just curious, are you using this method anywhere except maybe in tests?

2025-02-25 13:51 UTC, gregorbg commented on db/migrate/20241126084446_add_newcomer_reserved_spots_to_competitions.rb
> +    add_column :Competitions, :newcomer_reserved_spots, :integer, default: 0, null: false
Now that other PR is merged, so you can go full steam ahead with `null` support here

2025-02-25 13:52 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +          if !target_user.newcomer? && competition.newcomer_reserved_spots > 0
Now that other PR is merged, so you can rethink `null` support

2025-02-26 05:22 UTC, dunkOnIT commented on app/models/competition.rb
> +    newcomer_reserved_spots
Done

2025-02-26 05:28 UTC, dunkOnIT commented on app/models/competition.rb
> +  MAX_NEWCOMER_SPOTS_RESERVED_FRACTION = 0.5
Changed to `NEWCOMER_MONTH_RESERVATIONS_FRACTION` which isn't _much_ shorter but perhaps acceptably not-massive. My next suggestions would be just `NEWCOMER_MONTH_RESERVATIONS` (ie, drop the "fraction")

2025-02-26 05:29 UTC, dunkOnIT commented on app/models/user.rb
> +  scope :newcomer_month_eligible, -> { where(wca_id: nil).or(where('wca_id LIKE ?', "#{Time.current.year}%")) }
Ooh, that's nice - changed!

2025-02-26 05:32 UTC, dunkOnIT commented on app/models/competition.rb
> +  end
Moved!

2025-02-26 05:34 UTC, dunkOnIT commented on app/models/user.rb
> +  def newcomer?
Using it in tests, but also in `registration_checker:196`:
```ruby
          if !target_user.newcomer? && competition.newcomer_month_reserved_spots > 0
```

2025-02-26 06:13 UTC, gregorbg commented
Best wishes from RuboCop :wink:

2025-02-26 10:53 UTC, gregorbg requested changes

2025-02-26 10:53 UTC, gregorbg commented on app/models/user.rb
> +  def newcomer?
Then that reference should probably be `if !target_user.newcomer_month_eligible?`, or not??!

2025-02-26 10:53 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +          if !target_user.newcomer? && competition.newcomer_month_reserved_spots > 0
See my other remark above

2025-02-26 10:53 UTC, gregorbg commented on spec/controllers/competitions_controller_spec.rb
> +        FactoryBot.create_list(:registration, 3, :pending, :first_timer, competition: competition)
This is now a bit inconsistent with the `newcomer` / `newcomer_month_eligible` thingy above

2025-02-26 10:53 UTC, dunkOnIT commented on spec/controllers/competitions_controller_spec.rb
> +        FactoryBot.create_list(:registration, 3, :pending, :first_timer, competition: competition)
Yep this is the result of an over-eager grep/replace, I think

2025-02-26 11:16 UTC, dunkOnIT commented on lib/registrations/registration_checker.rb
> +          if !target_user.newcomer? && competition.newcomer_month_reserved_spots > 0
Definitely agree - why aren't my tests failing then?

2025-02-26 11:43 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +            competition.registrations.competing_status_accepted.count >= competition.competitor_limit
Are you trying to tell me we never checked competitor limits before?!

2025-02-26 12:20 UTC, gregorbg requested changes

2025-02-26 12:29 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +              (available_spots <= competition.newcomer_month_reserved_spots_remaining) && competition.registration_currently_open?
Why are you bothering to check `competition.registration_currently_open?` here, but not during the "general" competitor limit check above?

From my gut feeling, it should either be both or none.

2025-02-26 12:30 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +            available_spots = competition.competitor_limit - competition.registrations.competing_status_accepted.count
I think you can reuse the `competition.registrations.competing_status_accepted.count` part. If you wanna be very sneaky, you can even reuse the whole `available_spots` variable, and for the "general" check above you throw if `available_spots <= 0`.

2025-02-26 12:30 UTC, gregorbg commented on lib/registrations/registration_checker.rb
> +            available_spots = competition.competitor_limit - competition.registrations.competing_status_accepted.count
(but the latter is really just personal taste, feel free to keep it the way it is as you see fit.)

2025-02-26 12:45 UTC, gregorbg commented on app/models/registration.rb
> +    accepted.joins(:user).merge(User.newcomer_month_eligible).count
```suggestion
    joins(:user).merge(User.newcomer_month_eligible).accepted_count
```

2025-02-26 12:51 UTC, dunkOnIT commented on lib/registrations/registration_checker.rb
> +              (available_spots <= competition.newcomer_month_reserved_spots_remaining) && competition.registration_currently_open?
If registration is closed and the only people left for an organizer to accept are non-newcomers, we don't want the organizer's attempt to accept them being blocked by the newcomer limit. 

Although now that I've typed it out I'm not fully convinced - because it may well be the case that once registration is closed the organizer still wants to respect the newcomer month reserved spots

2025-02-27 08:06 UTC, merged