Edit Person Requests page in WRT panel
thewca/worldcubeassociation.org pull request #10451
Opened 2024-12-18 11:26 UTC by danieljames-dj

This PR creates a new page in WRT panel which lists all the tickets of type 'edit person'. The `TicketsList` component is made in a way that this can be reused for other components as well in future.

2025-01-03 12:36 UTC, gregorbg requested changes

2025-01-03 12:36 UTC, gregorbg commented on app/models/ticket.rb
> +    user_stakeholders(user).any?
I vaguely remember that you did a similar check in other, already-existing controller methods.
Can you go back and check whether you can re-use this new method in other places, now that you've created it?

2025-01-03 12:36 UTC, gregorbg commented on app/models/ticket.rb
> +    user_stakeholders(user).any?
Also, I want to note that this query can become very expensive very quickly. In a lot of developers' minds (who aren't familiar with the in-depth implementation for your tickets) the intuition is that "a simple boolean method that gives a Yes-No answer surely will just to some simple `==` comparison(s)". But the truth is that even in this early stage, the `user_stakeholders` already does a lot of heavy lifting, loading roles and stuff under the hood.

So _at least_ a warning comment should be warranted, and potentially we even need to think about a better optimization.

2025-01-03 12:36 UTC, gregorbg commented on app/webpacker/components/Panel/pages/EditPersonRequestsPage/index.jsx
> +    </>
Can't you just loop over `ticketStatuses.edit_person` and create this copy-pasted "Header+TicketsList" thing on-the-fly?

2025-01-03 12:36 UTC, gregorbg commented on app/controllers/tickets_controller.rb
> +        ticket.metadata.status == status
If `metadata` is generic, how do you even know it will always have a `status` variable?

And if you know that every metadata definitely always has a `status` variable, then why is it part of `metadata` and not part of the `Ticket` entity itself?

2025-01-03 12:36 UTC, gregorbg commented on app/controllers/tickets_controller.rb
> +    tickets = sort(tickets, sort_param, SORT_WEIGHT_LAMBDAS)
Where is this `sort` method coming from?

2025-01-03 12:36 UTC, gregorbg commented on app/controllers/tickets_controller.rb
> +    paginate json: tickets
Paginate won't really help you if you're already loading everything from the DB into memory anyways. In this case, pagination turns into "nice cosmetic" for slicing out the part of the pre-loaded array that the frontend wants, but before it can slice, all tickets need to be loaded anyways.

This is a huge waste of resources. `paginate` can really unfold its magic when you're building a database query and then passing on that query builder directly. Because then the pagination will translate this to a `LIMIT ... OFFSET ...` query making it beautifully efficient.

2025-01-08 10:44 UTC, danieljames-dj commented on app/models/ticket.rb
> +    user_stakeholders(user).any?
The PR is merged, so removed this method. (looks like I forgot to reply the previous message, it was still in draft. Sending all of them together now)

2025-01-08 10:58 UTC, danieljames-dj commented on app/controllers/tickets_controller.rb
> +        ticket.metadata.status == status
Oh yes, it's not necessary that `status` is there always theoretically. I've added `&`.

2025-01-08 10:58 UTC, danieljames-dj commented on app/controllers/tickets_controller.rb
> +    tickets = sort(tickets, sort_param, SORT_WEIGHT_LAMBDAS)
It's the same `sort_helper` we used for roles.

2025-01-08 10:58 UTC, danieljames-dj commented on app/controllers/tickets_controller.rb
> +    paginate json: tickets
I understand that paginate won't help in efficiency here. The reason why I added paginate is for the same purpose why we have paginate in user_roles: in case we decide to list the tickets in multiple pages instead of single page, this will be helpful.

I understand that if I need to show 100 tickets, in backend it will fetch all the 10000 tickets and then just cut the first 100. But I'm just focussing on frontend for now. I've added a comment for the same. Hope it's fine, let me know if I can do something to make it better.

(I have a feeling that some kind of relation stuffs like I did in `can_user_access?` might help, but I didn't spend time for that yet. Also, I have a feeling that the filtering and sorting is going to be much more complicated in future like user_roles, so in future this might become infeasible)

2025-01-09 04:52 UTC, gregorbg approved these changes

2025-01-09 04:52 UTC, gregorbg commented on app/controllers/tickets_controller.rb
> +    paginate json: tickets
Okay. I am not 100% happy with that reasoning, especially the part about "I have a feeling that the filtering and sorting is going to be much more complicated in future like user_roles, so in future this might become infeasible". If our database models are so convoluted that SQL-level filtering is impossible, we will have to redesign the database models.

But anyways, since you're integrating this feature step by step and the scope is quite limited for now, I'll approve.

2025-01-09 06:32 UTC, danieljames-dj commented
Thanks Gregor

2025-01-09 06:32 UTC, merged