Store country band details in database
thewca/worldcubeassociation.org pull request #10476
Opened 2024-12-25 04:02 UTC by danieljames-dj

This PR aims at removing some hard-coding related to dues details. This will help to make the changes quickly in case we need to make some change in dues in future.

2025-01-04 11:18 UTC, gregorbg requested changes

2025-01-04 11:18 UTC, gregorbg commented on app/controllers/country_bands_controller.rb
> +    unless CountryBandDetail.distinct.pluck(:number).include?(@number)
In case of CountryBand, where there's only like 5 or so entries the whole time, loading all values from the DB into memory won't be a big problem. But in general, loading the whole column into memory just for a simple `include?` check is a _big_ problem, so let me show you the cool SQL way
```suggestion
    unless CountryBandDetail.exists?(number: @number)
```

2025-01-04 11:18 UTC, gregorbg commented on app/controllers/country_bands_controller.rb
> +    unless CountryBandDetail.distinct.pluck(:number).include?(@number)
This (roughly, not sure how Rails does internal optimizations exactly) translates to a `SELECT 1 FROM country_bands WHERE number = 3` query

2025-01-04 11:18 UTC, gregorbg commented on db/migrate/20241225031242_populate_country_band_details.rb
> +  def change
This should be `def up`. Then you can also create a `def down` which does `CountryBandDetail.delete_all` or similar.

2025-01-04 11:18 UTC, gregorbg commented on lib/dues_calculator.rb
> +    registration_fee_dues_us_dollars = input_money_us_dollars * country_band_detail.due_percent_registration_fee.to_f/100
Spaces around the `/` division sign please

2025-01-04 11:18 UTC, gregorbg commented on lib/dues_calculator.rb
> +    return nil unless country_band_detail
Is our code prepared to handle a `nil` return value? The previous implementation was returning `0` If the `country_band.present?` check failed.

2025-01-04 11:18 UTC, gregorbg commented on lib/dues_calculator.rb
> +    return nil unless country_band_detail
Also, you can check `country_band_detail.present?`. It's a bit more readable than this "hacky" null check.

2025-01-14 12:27 UTC, gregorbg requested changes

2025-01-14 12:27 UTC, gregorbg commented on lib/dues_calculator.rb
> +    country_band_detail = CountryBandDetail.find_by(number: country_band)
You're completely ignoring your new `belongs_to` association here.

2025-01-29 14:27 UTC, danieljames-dj commented on app/models/country_band.rb
> +  belongs_to :country_band_detail, foreign_key: :number, primary_key: :number
Or in other words, I'll not have tight coupling between CountryBand and CountryBandDetail, instead CountryBand table will represent the band number of a country (maybe in future we can introduce start_date and end_date as well if we need the history of bands of a country). From the CountryBandDetails table, we can get the active details of a country band.

2025-01-29 14:27 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    country_band_detail = CountryBandDetail.find_by(number: country_band)
Oh sorry, changed it.

2025-01-29 14:27 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    registration_fee_dues = Money.new(registration_fees * (country_band_detail&.due_percent_registration_fee.to_f || 0) / 100, "USD")
Cleaned it a bit

2025-01-29 14:27 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    country_band_dues = Money.new(country_band_detail&.due_amount_per_competitor_in_cents || 0, "USD")
Cleaned it a bit

2025-02-05 10:41 UTC, gregorbg requested changes

2025-02-05 10:41 UTC, gregorbg commented on app/views/country_bands/_show_band.html.erb
> +    (<%= t("country_bands.due_value", value: country_band_detail.due_amount_per_competitor_in_cents.to_f / 100) %>)
I'm 60% sure you don't need the `to_f`

2025-02-05 10:41 UTC, gregorbg commented on app/models/country_band_detail.rb
> +class CountryBandDetail < ApplicationRecord
You can specify a `belongs_to :country_band` association by providing `primary_key: :number` and `foreign_key: :number` I think.

2025-02-05 10:41 UTC, gregorbg commented on app/models/country_band_detail.rb
> +class CountryBandDetail < ApplicationRecord
Don't confuse these with SQL `PRIMARY KEY` and `FOREIGN KEY`. The options I'm talking about here are (easily misunderstandable) Rails AR vocabulary, which means "the key [i.e. column] where I look up information in the foreign [i.e. pointing to] model, or in myself [i.e. primary]".

2025-02-05 10:41 UTC, gregorbg commented on app/models/country_band.rb
> +  end
As per my other comment in `CountryBandDetail`, I think you can solve this via a `has_many` relation.

2025-02-05 10:41 UTC, gregorbg commented on db/schema.rb
> +    t.integer "due_amount_per_competitor_in_cents", null: false
Maybe name this column `due_amount_per_competitor_us_cents` to make clear that the currency is pre-defined?

2025-02-05 10:41 UTC, gregorbg commented on lib/dues_calculator.rb
> +    registration_fee_dues = Money.new(registration_fees * due_percent_registration_fee / 100, "USD")
I think you can do calculations with the money object directly:
```
my_fee = Money.new(2000, "USD")
some_percentage = my_fee * 0.8
```

2025-02-05 10:41 UTC, gregorbg commented on lib/dues_calculator.rb
> +    due_percent_registration_fee = country_band_detail&.due_percent_registration_fee.to_f || 0
Again, I think you don't need the `to_f`. Ruby is very flexible with numbers.

2025-02-05 10:41 UTC, gregorbg commented on app/models/country_band.rb
> -  validates_inclusion_of :number, in: BANDS.keys.freeze
Can you hard-code the range from 0 to 5 instead of just completely deleting the line?
I know hard-coding is not very pretty, but effectively it was already hard-coded before (through an intermediate step which was getting the keys from the hard-coded hash)

2025-02-05 10:41 UTC, gregorbg commented on spec/models/country_band_spec.rb
> +    expect(cb).to be_invalid_with_errors(country: ["must exist"])
Regarding my other comment above, feel free to re-add the previous "number not included in the list" validation.

2025-02-05 10:41 UTC, gregorbg commented on spec/models/country_band_spec.rb
> +    expect(cb).to be_invalid_with_errors(country: ["must exist"])
Also, why did the `country` validation that you're testing now not exist/fail before?

2025-02-06 06:20 UTC, danieljames-dj reviewed
@gregorbg Thanks for your review, I've partially attended your comments. But since some changes are clashing with changes in https://github.com/thewca/worldcubeassociation.org/pull/10767, I'll wait for that PR to get merged before attending the remaining.

2025-02-06 06:20 UTC, danieljames-dj commented on app/models/country_band.rb
> -  validates_inclusion_of :number, in: BANDS.keys.freeze
Okay done.

2025-02-06 06:20 UTC, danieljames-dj commented on app/models/country_band_detail.rb
> +class CountryBandDetail < ApplicationRecord
Okay done

2025-02-06 06:20 UTC, danieljames-dj commented on app/models/country_band.rb
> +  end
Done

2025-02-06 06:20 UTC, danieljames-dj commented on app/models/country_band_detail.rb
> +class CountryBandDetail < ApplicationRecord
Oh wait, removed it for now. But looks like the association is not used anywhere, is it still needed to have this association here?

2025-02-06 06:20 UTC, danieljames-dj commented on spec/models/country_band_spec.rb
> +    expect(cb).to be_invalid_with_errors(country: ["must exist"])
Added back that error. I just realized the country validation test was already there in the unit test just before this.

2025-02-12 02:29 UTC, gregorbg commented on app/models/country_band.rb
> +  validates_inclusion_of :number, in: (0..5).to_a
Rails has special `numericality` validators for cases like this: https://guides.rubyonrails.org/active_record_validations.html#numericality

2025-02-12 04:15 UTC, danieljames-dj reviewed
One more issue remaining, I've pinged you in slack.

UPDATE: The one issue is resolved, it was related to `invert_where` and the details are explained in https://github.com/thewca/worldcubeassociation.org/pull/10818.

2025-02-12 04:15 UTC, danieljames-dj commented on db/schema.rb
> +    t.integer "due_amount_per_competitor_in_cents", null: false
Okay changed.

2025-02-12 05:14 UTC, gregorbg commented on app/views/country_bands/_show_band.html.erb
> +    (<%= t("country_bands.due_value", value: country_band_detail.due_amount_per_competitor_in_cents.to_f / 100) %>)
Then divide by `100.0`

2025-02-12 05:15 UTC, gregorbg commented on lib/dues_calculator.rb
> +    due_percent_registration_fee = country_band_detail&.due_percent_registration_fee.to_f || 0
But `x / 100.0` will return `0.05` :wink:

2025-02-12 05:16 UTC, danieljames-dj commented on app/views/country_bands/_show_band.html.erb
> +    (<%= t("country_bands.due_value", value: country_band_detail.due_amount_per_competitor_in_cents.to_f / 100) %>)
Okay done

2025-02-12 05:19 UTC, gregorbg requested changes

2025-02-12 05:19 UTC, gregorbg commented on spec/models/country_band_spec.rb
> -    expect(cb).to be_invalid_with_errors(number: ["is not included in the list"])
Can you please keep this country-related smoke check in a separate test?

2025-02-12 05:19 UTC, gregorbg commented on lib/dues_calculator.rb
> +    registration_fees = Money.new(base_entry_fee_lowest_denomination, currency_code).exchange_to("USD")
The name should make clear that we're dealing with the reg fees in US dollars.

2025-02-12 05:19 UTC, gregorbg commented on lib/dues_calculator.rb
>    def self.dues_per_competitor_in_usd(country_iso2, base_entry_fee_lowest_denomination, currency_code)
You're doing an awful lot of `&.` and `|| 0` safe navigation throughout the whole method. Most of if seems to be related to the fact that `country_band_detail` can be null. When and under which circumstances can this happen? And if it happens, can you just `return` early and then after the return be sure that the CB details exist?

2025-02-12 05:26 UTC, danieljames-dj commented on spec/models/country_band_spec.rb
> -    expect(cb).to be_invalid_with_errors(number: ["is not included in the list"])
That is already there in the previous unit test, is that fine?

2025-02-12 05:26 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    registration_fees = Money.new(base_entry_fee_lowest_denomination, currency_code).exchange_to("USD")
Okay renamed.

2025-02-12 05:26 UTC, danieljames-dj commented on lib/dues_calculator.rb
>    def self.dues_per_competitor_in_usd(country_iso2, base_entry_fee_lowest_denomination, currency_code)
> When and under which circumstances can this happen

I think it happens only if there is no active country_band_detail for a country.

I've returned early as you suggested.

2025-02-12 05:32 UTC, gregorbg requested changes

2025-02-12 05:32 UTC, gregorbg commented on lib/dues_calculator.rb
> +    return nil if country_band_detail.nil?
If you move this statement one line higher, you can save yourself an extra call to `exchange_to` :wink:

2025-02-12 05:32 UTC, gregorbg commented on lib/dues_calculator.rb
> +    due_percent_registration_fee = country_band_detail.due_percent_registration_fee
Is declaring this variable super-duper necessary? It's only used once below...

2025-02-12 05:32 UTC, gregorbg commented on lib/dues_calculator.rb
> +    due_amount_per_competitor_us_cents = country_band_detail.due_amount_per_competitor_us_cents
Same as above. this variable seems kinda redundant now

2025-02-12 05:39 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    return nil if country_band_detail.nil?
Okay, I thought of keeping inits at the beginning. I've moved the above line below now (same as you suggested). Hope it is fine now.

2025-02-12 05:39 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    due_percent_registration_fee = country_band_detail.due_percent_registration_fee
Okay removed.

2025-02-12 05:39 UTC, danieljames-dj commented on lib/dues_calculator.rb
> +    due_amount_per_competitor_us_cents = country_band_detail.due_amount_per_competitor_us_cents
Done

2025-02-12 05:45 UTC, gregorbg approved these changes

2025-02-12 05:45 UTC, gregorbg commented on spec/models/country_band_spec.rb
> -    expect(cb).to be_invalid_with_errors(number: ["is not included in the list"])
Okidoki!

2025-02-12 05:58 UTC, merged