Add 2024-01-01 Regulations to History
thewca/worldcubeassociation.org pull request #10480
Opened 2024-12-26 20:15 UTC by Nanush7

**!!! Do not merge before 2024-01-01 Regulations and Guidelines are released !!!**

@thewca/wrc-team please review in case there's something wrong. It's a simple change, but I couldn't test it because docker-compose is not working for me.

We may need to wait for https://github.com/thewca/wca-regulations/pull/1191 as well.

2024-12-26 22:53 UTC, Randomno commented
#9376

2025-01-03 06:48 UTC, gregorbg requested changes

2025-01-04 10:55 UTC, gregorbg commented on app/views/regulations/history.html.erb
> +      <ul>
Ah, thanks!

2025-01-04 10:56 UTC, gregorbg approved these changes

2025-01-04 10:57 UTC, gregorbg commented
LGTM, can this be merged now? (Seeing that 2025-01-01 regs are released)

2025-01-04 16:08 UTC, Nanush7 commented
Yes!(and please see the latest WRC-WST email).

2025-01-05 05:56 UTC, merged