Updated qualification explainer to 'on or before'
thewca/worldcubeassociation.org pull request #10499
Opened 2024-12-31 14:48 UTC by dunkOnIT

@timreyn this addresses one of your comments on the PR where we changed the qualification logic. Your full comment was: 

> Can you also update the text on https://www.worldcubeassociation.org/competitions/WC2025#competition-events ? Under "Qualification" it says "by DATE_MINUS_ONE", and at the bottom it says "before".

As far as I can see, we are now showing the date itself, not date-minus-one - can you confirm this is the case? 

![image](https://github.com/user-attachments/assets/a0430818-4c21-4d73-91a7-1b396635ef65)

![image](https://github.com/user-attachments/assets/b7f7ab9b-ba34-4e2f-9f20-1780b52691c1)

2025-01-01 10:31 UTC, gregorbg requested changes

2025-01-01 10:31 UTC, gregorbg commented on config/locales/en.yml
>          qualification_some_events_html: "Qualification times in %{events} must be set before <b>%{date}</b>."
:upside_down_face:

2025-01-03 07:32 UTC, dunkOnIT commented
Ah thanks! I literally just grepped for the text I saw on WC2025 page, didn't realize we had 2 different keys

2025-01-03 10:05 UTC, gregorbg approved these changes

2025-01-03 10:05 UTC, merged