Update dockerfile to use Node v16 LTS
thewca/worldcubeassociation.org pull request #6935
Opened 2022-05-28 22:33 UTC by dmint789

Our dockerfile doesn't build a valid image anymore. This PR updates the dockerfile to use Node 16 LTS and fixes the problem.

2022-05-28 22:49 UTC, dmint789 commented
Last time I made this fix, @gregorbg asked to implicitly use version 14 to avoid issues with some dependencies needing a specific version. I decided to stick to lts this time, as I believe it's more future-proof, seeing as this is the second time our dockerfile needed to be updated in just a year.

2022-05-29 01:57 UTC, gregorbg requested changes
The correct process would still be to pin this to "whatever is used in our current Chef infrastructure provisioning" as per https://github.com/thewca/worldcubeassociation.org/blob/master/chef/site-cookbooks/wca/recipes/default.rb#L8.

I can appreciate the logic that an LTS release "should work", but I want to keep our versions in sync as good as possible. Believe me, there have been times where implicitly causing a newer version of Node than we expected _has_ caused problems in the past.
Also, changing a Dockerfile twice in a couple of months is waaay below average for usual Docker workflows 😄

2022-05-29 01:57 UTC, gregorbg commented on WcaOnRails/Dockerfile
> +RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
Please change to `setup_16`

2022-05-29 11:25 UTC, gregorbg approved these changes

2022-05-29 11:25 UTC, dmint789 commented
Wow, that was fast @gregorbg haha. Thanks for approving quickly.

2022-05-29 11:27 UTC, gregorbg commented
I was coincidentally browsing GitHub anyways when your new commit came in :D
Feel free to merge as soon as the checks pass.

2022-05-29 11:37 UTC, merged