Expose a user's ongoing competitions
thewca/worldcubeassociation.org pull request #6980
Opened 2022-06-08 12:49 UTC by coder13

This calculates if a competition is ongoing by looking at if it has 1. started and 2. probably not over.
It then exposes this as a query param when fetching `/users/{userid}`

This directly fixes #6970 but I'd like to also, in a later PR, expose a route `/api/v0/users/{userid}/competitions` to fetch all of a user's competitions.

Alternatively, I could modify the `/api/v0/competitions` to add a query param to search for competitions with registrations containing a certain userId.

2022-06-08 13:07 UTC, gregorbg requested changes
Thanks for the quick implementation!
One nitpick about code reuse.

Also, please do not hesitate to pick up #6261 if you're interested, Saransh doesn't seem to be available to finish it right now.

And for the love of god please don't introduce a user ID filtering query param to the `/competitions` endpoint 😂

2022-06-08 13:07 UTC, gregorbg commented on WcaOnRails/app/controllers/api/v0/api_controller.rb
> +                                          .select(&:ongoing?)
The entire notion of querying a user's competitions is identical to `upcoming_competitions` above.

```ruby
user.registrations
.accepted
.includes(competition: [:delegates, :organizers, :events])
.map(&:competition)
```

Please _at least_ move that part out of the two if-blocks and only apply the `select` filter based on which query param is present.
Ideally, consider moving that entire block into the `user.rb` model as a kind of `accepted_competitions` method. (although that's arguably a bit out of scope of this PR, so I leave it to you to decide)

2022-06-08 14:01 UTC, coder13 commented
> And for the love of god please don't introduce a user ID filtering query param to the /competitions endpoint joy

haha, ok. Is this a performance thing?

Is it because you query for all competitions -> for all registrations where registrations contains user Id?

Just spitballing but we could even do a `/api/v0/competitions/mine` to mirror how it is in terms of the pages.

2022-06-10 00:08 UTC, gregorbg commented
> > And for the love of god please don't introduce a user ID filtering query param to the /competitions endpoint joy
> 
> haha, ok. Is this a performance thing?
> 
> Is it because you query for all competitions -> for all registrations where registrations contains user Id?
> 
> Just spitballing but we could even do a `/api/v0/competitions/mine` to mirror how it is in terms of the pages.

It is mostly for avoiding feature duplication. I generally don't want to have the exact same information be available in two different ways, as that tends to confuse people who use the API externally.
We also currently don't have a really fleshed-out design spec, so I'd rather not take each and every idea about our API and implement them straight away.

2022-06-10 00:14 UTC, gregorbg approved these changes
Thanks for making the adjustments!

2022-06-10 06:54 UTC, merged

2022-06-10 12:15 UTC, coder13 commented
Thanks for merging!