Use content_or_options in label_tag to bypass humanize method [competitions page / translation]
thewca/worldcubeassociation.org pull request #7304
Opened 2022-10-20 22:22 UTC by AnnikaStein

Summarizing the original problem described in https://github.com/thewca/worldcubeassociation.org/issues/7299: When passing only one parameter inside a `label_tag`, this automatically calls the `humanize` method. For the German translation of two keys at the competitions page, this leads to unwanted behavior: we would like to have several words capitalized, not only the first one at the beginning of the translated key.

This PR now explicitly instructs the `label_tag` to write the content exactly as specified in the locales/*.yml file and bypasses the humanize method. From what I can tell, this should not cause trouble for non-German translations, because we usually expect the text to appear exactly as translated with the i18n keys and don't expect `humanize` to take care of underscores or capital letters. As this seems to be the first time this needs to be introduced for this repository (the search only leads to the issue quoted above), I made it explicit in the fix by writing keyword arguments instead of positional arguments only.

Result in local docker build:
<img width="623" alt="Bildschirmfoto 2022-10-21 um 00 13 56" src="https://user-images.githubusercontent.com/53974095/197069159-28cfb471-16da-47b1-a2cb-13e08af5042b.png">

Fixes https://github.com/thewca/worldcubeassociation.org/issues/7299

2022-10-29 09:47 UTC, gregorbg commented
Thank you for the incredible thorough investigation! Actually, it seems that `label_tag` in Rails is supposed to be used like so:
```ruby
label_tag(html_id, display_text)
```
such that the first argument does not need to be a translated string from our `t('...')` method. In context, the labels control form elements like so:

```ruby
<% Event.official.each do |event| %>
<span class="event-checkbox">
  <%= label_tag "checkbox-#{event.id}", "Awesome human readable event: #{event} with CapiTAliZatioN!!1!111!" %>
  <%= check_box_tag "checkbox-#{event.id}" %>
</span>
<% end %>
```

So you should change the code to have the first parameter be a computer-readable ID. You can invent anything really.

2022-10-29 09:48 UTC, gregorbg requested changes
See my longer explanation post for the requested changes.

2022-10-29 18:44 UTC, AnnikaStein commented
Thank you @gregorbg for your feedback! Indeed it sounds good to make a distinction between human-readable parts and the actual identifier.
Now, I currently can't access the device with which I'm usually coding for some more days 🏥, would you mind co-authoring this PR? It looks like it's already quite close to what you suggested, just the mapping between the identifiers needs to be added.

2022-11-01 23:58 UTC, gregorbg commented
I don't mind if this stays open for a couple more days.

2022-11-03 08:21 UTC, AnnikaStein commented
Finally got to work on this again. The two checkboxes now use the computer-readable IDs as requested to map them to their `label_tags`.

The HTML renders as

```
<div id="registration-status" class="form-group registration-status-selector">
  <input type="checkbox" name="show_registration_status-checkbox" id="show_registration_status-checkbox">
  <label for="show_registration_status-checkbox">Zeige Anmeldestatus-Symbol</label>
</div>
<div id="cancelled" class="form-group cancel-selector">
  <input type="checkbox" name="show_cancelled-checkbox" id="show_cancelled-checkbox">
  <label for="show_cancelled-checkbox">Zeige abgesagte Wettbewerbe</label>
</div>
```

So each label knows for which checkbox it is used for.

@gregorbg Did I understand the requested changes correctly? 🙂

2022-11-03 08:33 UTC, gregorbg commented
Yup, all fine. Although the extra `#{:foo}-checkbox` Interpolation probably isn't necessary. The important part is not that it ends in `-checkbox`, but rather that it makes a distinction between the ID (as first argument) and the human label string (as second argument) at all.

Feel free to remove the `-checkbox` Interpolation if you want to, but I won't block the merge at this point.

2022-11-03 08:47 UTC, AnnikaStein commented
Ok, thanks! Just used the same pattern that you gave in the example, as I found it quite instructive and a nice cross-check that this mapping works as expected. Like, despite it being computer-readable, there's still the additional string around that makes it clear for us, so I, as an absolute beginner, came to prefer this extra hint. Otherwise I think I understood the explanation (i.e. that `-checkbox` is not the important part). :+1:

2022-11-04 14:27 UTC, merged