changed bullet to be disabled by default
thewca/worldcubeassociation.org pull request #7480
Opened 2022-12-17 13:38 UTC by dunkOnIT

Set `disable_bullet=true` in `.env.development`, which will make bullet optimiser opt-in only, and not confuse noobs like me

2022-12-17 14:30 UTC, gregorbg commented
On second thought, how about changing it to `ENABLE_BULLET=false` by default? This would be less convoluted, but it will require changing the code in `env_vars.rb` as well as all occurences (should only be one anyways=

2022-12-17 15:43 UTC, dunkOnIT commented
I love it when you think twice

2022-12-18 03:16 UTC, gregorbg commented
Gives you a nice opportunity to practice on some Rails code :smile:

2023-01-21 17:26 UTC, FinnIckler commented
can this be merged?

2023-01-24 04:18 UTC, gregorbg commented
Technically yes, but I'd prefer to update this to a state where the vars are called `BULLET_ENABLED`.
Bullet is an inspection tool that should be disabled by default and only _enabled_ consciously when you want to investigate some performance issues or perform benchmarks.

2023-01-25 06:43 UTC, dunkOnIT commented
Happy to make the requested changes, just a bit snowed under at the moment!

2023-03-17 19:45 UTC, gregorbg requested changes
Somehow the local changes to your structure.sql made it into the diff. Please clear them out before merging.

2023-03-17 19:45 UTC, gregorbg commented on WcaOnRails/config/environments/development.rb
> +    Bullet.enable = !EnvVars.ENABLE_BULLET?
NB You have to flip the negation here!

2023-03-18 04:52 UTC, dunkOnIT commented
Removed `structure.sql` diff and flipped negation in `development.rb` - whoops :sweat:

2023-03-18 05:12 UTC, dunkOnIT commented
The failing test is confusing me:
> `SuperConfig::MissingEnvironmentVariable: ENABLE_BULLET is not defined.`

Looks to me like this is being run in the test environment (`RACK_ENV: test`). `ENABLE_BULLET` isn't defined there, but `DISABLE_BULLET` never was either. I see why it should be defined - `env_vars.rb:12` makes it mandatorry unless the environment is `production`. 

I believe the fix is to define `ENABLE_BULLET` somewhere in `test.rb` - but I'd like to understand why this wasn't causing an error before?

2023-03-18 20:45 UTC, gregorbg commented
You're close. The configuration values are loaded from the `.env.*` files in `WcaOnRails`. So the error is correct insofar as `.env.test` still contains the old `DISABLE_BULLET` and SuperConfig is rightfully complaining that `ENABLE_BULLET` is not defined in that file :upside_down_face:

2023-03-19 07:02 UTC, dunkOnIT commented
Ah thanks! Thought I had grepped for `DISABLE_BULLET` in the project folder, but clearly not (:

2023-04-02 11:26 UTC, gregorbg approved these changes

2023-04-02 11:26 UTC, merged