Allow non-admins to close registration when the competitor limit is reached.
thewca/worldcubeassociation.org pull request #7526
Opened 2023-01-05 21:31 UTC by DanielEgdal

Giving refunds can be a big expense to organisers, if a waiting list gets too large before WCAT can action the closure. This PR should fix that issue.

2023-01-09 19:23 UTC, FinnIckler commented
Considering no tests failed, should we add a test for this?

2023-01-11 09:36 UTC, viroulep requested changes
For the record this would fix #6818 I think.

Thanks for the PR @DanielEgdal, I'm really looking forward to having this feature as it happens sometimes for us as well and it would be really awesome to cut down refund fees!

The implementation itself could look fine to me, but I believe it opens a behavior the WCAT would not be fine with: it would let organizers/delegates re-open/re-close registrations as they want when the registrations list is full.

There might be a way around this by letting them change the `registration_close` param only if registrations are actually still opened, but I think there is an even simpler solution: don't let organizers/delegates change this date, just provide a button to "close" the registrations with an action that set the `registration_close` param to `Time.now`.

Wether you want to give a shot to the alternate implementation or not, I think the PR should be changed a bit so that changing the registration closing date is not possible when registrations are already close.

2023-01-13 18:17 UTC, DanielEgdal commented
Allow should be good now! 
![image](https://user-images.githubusercontent.com/28397408/212391230-af3ced72-a2f3-46d7-857f-9b00eb40928f.png)

3 working test cases added as well.

2023-01-17 08:57 UTC, viroulep approved these changes
Thanks for changing the implementation, it looks good to me!

Before this is merged I believe the commits should be squash into a single commit with a meaningful message (but I believe whoever merge this from WST can do this upon merging using github's UI).

When this goes live I think it's worth to inform WCA Staff that this button exists now :)

2023-01-17 08:57 UTC, viroulep commented on WcaOnRails/spec/controllers/competitions_controller_spec.rb
> +        comp_with_full_reg = FactoryBot.create(:competition, :registration_open, competitor_limit_enabled: true, competitor_limit: 1, competitor_limit_reason: "we have a tiny venue")
Thanks for the good laugh xD

2023-01-17 12:47 UTC, merged

2023-01-17 12:48 UTC, FinnIckler commented
Thanks daniel!