Add support for non-competing staff.
thewca/worldcubeassociation.org pull request #7601
Opened 2023-02-04 14:04 UTC by timreyn

When persons are included in the WCIF patch who are not registered, they are now assumed to be non-competing staff, rather than silently being ignored. This allows them to have an entry in Registrations without having to sign up for events, which in turn allows them to be assigned to tasks like judging. Because they are not marked as "accepted", they do not appear in the registrations table or psych sheet.

This doesn't add a UI for adding non-competing staff; this is left up to tools that assign tasks like Groupifier, and an in-development tool for CubingUSA Nationals.

Non-competing staff also appear in a separate table on the edit registrations page.

Fixes #7491.

2023-02-06 13:08 UTC, dunkOnIT commented
Does this PR cover functionality for adding non-competing staff via the registrations page / allowing them to sign up? Or is it purely through WCIF data imports? (Just asking for clarity/scope's sake, no particular preferences either way)

2023-02-06 13:19 UTC, timreyn commented
@dunkOnIT This is purely through WCIF imports, for a few reasons:

- ease of implementation: given that I don't expect this to be a very widely-used feature, I didn't want to take the time to implement a UI.
- interaction with registrations flow rebuild: I don't know enough about the plans for the registration rebuild to know whether any work I did on a UI here would be replaced by that work.
- separation of responsibilities: It's not totally clear whether non-competing staff should be the responsibility of the WCA site, or tools like groupifier which are already responsible for everything related to staff assignments.

2023-02-06 13:21 UTC, dunkOnIT commented
Fully agree on all points @timreyn, thanks for the clarity. Additionally. I think we can expect that the competitions making use of this should have access to the software resources necessary to make such a WCIF import - whether by arrangement with WST or a developer on their team.

2023-02-08 15:53 UTC, FinnIckler requested changes
should we also deploy this to staging so we can make sure this is supported by third party tools like groupifier before this is merged? Not sure how we usually handle stuff like this.

2023-02-09 01:59 UTC, timreyn commented on WcaOnRails/app/models/competition.rb
> +      if !registration
I switched to that, then rubocop requested that I change the following line to ||= instead.

2023-02-09 09:58 UTC, FinnIckler commented on WcaOnRails/app/models/competition.rb
> +      if !registration
Wow, so many interesting operators in ruby. =|| Is the one to go to then

2023-02-09 12:04 UTC, timreyn commented
Re staging -- sure, I'm happy to help test Groupifier on staging.

2023-02-10 13:18 UTC, FinnIckler commented
Can you merge master into your branch as we merged some migrations

2023-02-10 13:19 UTC, FinnIckler commented
@jonatanklosko does a groupifier staging server exist or do you need to run your own locally and point it to WCA staging?

2023-02-10 13:30 UTC, jonatanklosko commented
@FinnIckler Groupifier doesn't have its own backend, it it's a purely client app talking to the WCA API. You can make it to talk to WCA staging instead by adding a param: https://groupifier.jonatanklosko.com/?staging=true :)

2023-02-10 13:32 UTC, timreyn commented
Merged master.

2023-02-13 15:00 UTC, timreyn commented
@FinnIckler just to confirm, were you planning to deploy this to staging? Happy to help test this once you do!

2023-02-13 15:30 UTC, FinnIckler commented
I tried but I am getting some weird errors when running `RAILS_ENV=staging bin/rake db:migrate` for your migrations and waiting for Gregor to get back to help

2023-02-17 17:17 UTC, gregorbg requested changes
Not a fan of introducing yet another boolean to the DB. If we absolutely have to (i.e. if this property cannot be derived automagically through a null-check or similar) then we should call it `is_competing`.

2023-02-17 17:20 UTC, coder13 commented
We already have a standard of having a null registrations for those who are in the persons array but not competing. 

Would it be posssible to use this to reference those people?
In the "roles[]" array could be values such as "staff-scrambler" or just "staff" and you could do with it as you wish.

One other idea was to reuse roles[] to also contain team name so for one person it could be like `roles: ["staff-scrambler", "staff-runner", "staff-judge", "blue stage"] to denote the jobs the person may do and their stage.

2023-02-17 17:35 UTC, timreyn commented
> Not a fan of introducing yet another boolean to the DB. If we absolutely have to (i.e. if this property cannot be derived automagically through a null-check or similar) then we should call it `is_competing`.

An alternate idea would be that people with zero events are considered non-competing. However, that would probably mean getting rid of the validation that people must be registered for at least one event, which seems not ideal. Having it as a boolean instead of just basing it on events lets us treat this as more of a special case, rather than just somebody who forgot to sign up for events whose registration should have been rejected.

Sure, happy to reverse the boolean!

2023-02-19 15:06 UTC, gregorbg commented
Thanks! And once again, the `structure.sql` nightmare :sweat_smile: Please make sure to only check in the changes relevant to the migration in this PR instead of the whole file.

2023-02-19 17:04 UTC, timreyn commented
Ugh, sorry for letting that slip through again! Done.

2023-02-26 18:21 UTC, gregorbg approved these changes

2023-02-26 18:23 UTC, merged