Added devise-jwt and jwt auth route
thewca/worldcubeassociation.org pull request #7986
Opened 2023-06-07 16:00 UTC by FinnIckler

This PR is a reference implementation for adding jwt to our devise workflow. This does not have to be merged for quite a while, but I will use it to implement our auth structure in the wca-registration repo.

This PR adds:
- a JWT creation secret (let's hope we will store this in vault by the time this is merged)
- a JWT payload for users that contain the wca_id and user_id (we might need to add more in the future and I will update this PR as necessary)
- a JWT auth route that the frontend can call to get a token (I really don't know how the CORS setting work on here right now but this might be accessible from other websites currently which we don't want)

The flow looks like this:
- The wca.org frontend serves the bundle for the micro service frontend
- The frontend contains code hitting the JWT auth route to get a token on requests
- The JWT token is sent to the microservice where it can be validated and used

I will link my corresponding PR on wca-registration here when it is done, please review both

2023-06-21 15:22 UTC, gregorbg requested changes
Minor changes as per Google Meet

2023-06-21 15:22 UTC, gregorbg commented on WcaOnRails/.env.test
> +DEVISE_JWT_SECRET_KEY=1ee0f7e7439ae477bb423e672e118704e1ed43eeeb4ac796c7a9ca3e0e7a431097e1eb976ce827cc94e7728e75cb2e91a0f3c7d8e6b1a3f7e9d5
see above.

2023-06-21 15:22 UTC, gregorbg commented on WcaOnRails/app/controllers/api/v0/api_controller.rb
> +    if !current_user
`unless`

2023-06-21 15:22 UTC, gregorbg commented on WcaOnRails/config/initializers/devise.rb
> +    jwt.secret = ENV.fetch("DEVISE_JWT_SECRET_KEY")
Please configure this in EnvVars via the existing `SuperConfig` integration

2023-06-21 15:22 UTC, gregorbg commented on WcaOnRails/app/models/jwt_denylist.rb
> +  self.table_name = 'jwt_denylist'
Please consider another name for the table so it adheres to Rails conventions

2023-11-01 17:33 UTC, closed without merging

2023-11-01 17:33 UTC, FinnIckler commented
Don't think it makes any sense to reuse this branch as it uses the old database structure. Will open a new one