Add Catalan translation
thewca/worldcubeassociation.org pull request #8234
Opened 2023-08-24 03:16 UTC by dunkOnIT

Based on https://github.com/thewca/worldcubeassociation.org/pull/6374. Still waiting on a reply from the translation submitter to add their user_id to /controllers/translations_controller.rb.

Please let me know if anything else is required here - this is a best guess attempt based on the Wiki docs and the linked PR :D

2023-09-08 10:00 UTC, gregorbg requested changes
You also need to teach our website overall that "Catalan exists" by adding an entry to `WcaOnRails/config/locales.rb`.

Plus I think the error output from the CI tries to tell you that the YAML syntax is malformed somewhere around line 850.

2023-09-08 10:00 UTC, gregorbg commented on WcaOnRails/app/assets/javascripts/fullcalendar/locales/ca.js
> +//= require fc_locales/cs.js
`cs` is Czech. You should import `ca`.

2023-09-08 10:00 UTC, gregorbg commented on WcaOnRails/app/assets/javascripts/locales/ca.js
> +//= require moment/cs.js
`ca`, not `cs`. See my other comment.

2023-09-10 03:32 UTC, dunkOnIT commented on WcaOnRails/app/assets/javascripts/fullcalendar/locales/ca.js
> +//= require fc_locales/cs.js
Silly mistakes - thanks!

2023-09-10 03:33 UTC, dunkOnIT commented
YAML fixed, all changes made. Only thing I'm no sure about if the flag_id for Catalan - but it doesn't really look like this is used anywhere in the code (which is for the best imo)

2023-09-11 08:37 UTC, gregorbg commented
The correct **country** locale (as opposed to **language** locale) is `es-ct` (or `es-CT` in some circumstances)

2023-09-19 10:19 UTC, gregorbg commented
Thanks for the YML fix, please correct the country code as well and then this can go live

2023-09-19 11:05 UTC, dunkOnIT commented
I've updated the flag_id to `es-ct` - not clear on whether the key in `locales.rb` should also be updated to `es-ct` (and placed under `es`. Based on your description I think so, but I'm not clear how a relationship is created between the locale and the translation if they don't share names/keys, so have left it as-is for no.

2023-09-19 11:15 UTC, gregorbg commented
Most parts in our code, including the keys in `locale.rb`, reference the **language**. That's the code `ca`.

The flag is an exception because it references the **region** which may or may not have a different ISO code.

As stated above, we generally care about languages so `ca` is fine unless explicitly required otherwise.

2023-09-19 11:28 UTC, dunkOnIT commented
Ok thanks, that makes sense and I've added a clarifying note in our translations documentation as well.

2023-09-19 11:32 UTC, dunkOnIT commented
Test failures may be from the new edit events tests merged into main (the failure looked familiar to the tests I looked through), so merging master and then re-pushing

2023-09-19 13:37 UTC, merged