Have registrations export generate wcif_status instead of single-letter
thewca/worldcubeassociation.org pull request #8288
Opened 2023-09-06 07:13 UTC by dunkOnIT

Still need to test locally - but I think if we just return the WCIF status in the endpoint we improve the CSV export considerably.

# Manual tests:
- [x] Exporting registrations in different states returns the WCIF states in the CSV
- [ ] Importing registrations with different WCIF states adds only accepted registrations (existing behaviour)
- [ ] Importing registrations with "a" states adds them as registrations (backwards compatibility)

2023-09-06 10:52 UTC, gregorbg requested changes
Syntax changes requested.

Also consider that this may have broad implications for people who currently rely on the CSV export. Might be worth digging through some logs to see how many times the registrations CSV route was actually hit, and sending an announcement email.

2023-09-06 10:52 UTC, gregorbg commented on WcaOnRails/app/views/registrations/export.csv.erb
> +  registration.wcif_status
You forgot a comma at the end of the line

2023-09-29 16:56 UTC, gregorbg approved these changes
Change fine per se, but please hold off with merging until we figured out how broad the implications of this change actually are (i.e. how many people rely on this CSV export)

2023-10-02 03:51 UTC, dunkOnIT commented
The current plan is to create backwards compatibility for CSV _imports_ by supporting either the letter or the status - that's the current blocker for this PR. I'll also ask around for anyone using the export function, though

2023-12-01 15:59 UTC, gregorbg commented
Kindly pinging this PR

2023-12-30 00:33 UTC, dunkOnIT commented
Pretty low priority for me compared to the Registration Service work, but I may pick this up as part of the WCIF/Registration Service integration I'll be starting soon

2025-03-27 09:31 UTC, dunkOnIT commented
Closing (at last!) in favour of #11165

2025-03-27 09:31 UTC, closed without merging