Update zh-CN.yml
thewca/worldcubeassociation.org pull request #8785
Opened 2024-01-29 17:47 UTC by 2016WUJI01

Update zh-CN.yml.
Maybe it need @notrichardpeng (Richard Jiankun Peng) to review those translations.

2024-01-30 10:06 UTC, gregorbg commented
> Maybe it need @notrichardpeng (Richard Jiankun Peng) to review those translations.

Thanks for your submission! If you can get any Chinese-speaking Delegate to vouch for you, we can add you to the list of verified translators and automatically merge any submissions you make

2024-01-30 19:59 UTC, notrichardpeng requested changes

2024-01-30 19:59 UTC, notrichardpeng commented on WcaOnRails/config/locales/zh-CN.yml
> +    spirit_footer: WCA精神
“WCA精神” 或 “WCA的精神” 都可以，但是感觉最好和上面的 "WCA的使命" 保持一样（用不用 “的”）

2024-01-30 19:59 UTC, notrichardpeng commented on WcaOnRails/config/locales/zh-CN.yml
> +    motions: 提议
“议案” 可能好一点

2024-01-31 02:36 UTC, 2016WUJI01 commented on WcaOnRails/config/locales/zh-CN.yml
> +    motions: 提议
Changed

2024-01-31 03:00 UTC, 2016WUJI01 commented on WcaOnRails/config/locales/zh-CN.yml
> +    motions: 提议
And I only changed two chinese words, But Ruby tests shows "All checks have failed".

2024-01-31 03:59 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +      text: 世界魔方协会负责管理魔方的比赛，这些魔方是通过转动一部分块来操作，通常称为“魔方”（twisty puzzles)。
Using `一部分块` feels a little bit unnatural to me.
Is there a better expression for this?

2024-01-31 04:07 UTC, 2016WUJI01 commented on WcaOnRails/config/locales/zh-CN.yml
> +      text: 世界魔方协会负责管理魔方的比赛，这些魔方是通过转动一部分块来操作，通常称为“魔方”（twisty puzzles)。
Maybe 转动魔方的一部分来操作 ?

2024-01-31 04:10 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +    mission_statement: 我们的使命是：在公平、平等的条件下，在更多国家举办更多、更多人、更有趣的比赛。
`在更多国家举办更多、更多人、更有趣的比赛。`
有点不通顺，不顺口

I think `more competitions in more countries with more people and more fun` can be expressed better with `在更多国家举办更多更有趣的比赛，并让更多人参与。`

2024-01-31 04:15 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +      <p>世界魔方协会负责管理魔方的比赛，这些魔方是通过转动一部分块来操作，通常称为“魔方”（twisty puzzles)。这些魔方中最著名的是三阶魔方，由匈牙利的鲁比克教授发明。这些魔方中的一部分被选为WCA的官方赛事项目。</p>
same as hash: ed77e4c `一部分块`

2024-01-31 04:22 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +    world_championship_content_html: '<p>每两年一次，我们将在比赛中决定谁是世界冠军。这些活动需要大量志愿者进行极其仔细的规划，并需要投入大量资金来预订场地并进行必要的准备。</p>'
`sanction` 没有翻译到

2024-01-31 04:24 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +    tax_deductible_note: 在美国，捐款可以免税。
tax-deductible 与 tax-free 不同
应该是`抵税`

2024-01-31 04:28 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +      donate_other: 其他方式捐款
Other ways to help is non-financial aid.

It should be 
`其他方式的协助` or `其他方式的帮助`

2024-01-31 04:34 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +        name: WCA市场组
Personally, I prefer `市场营销组` or `营销组` 
Just `市场组` 怪怪的

2024-01-31 04:35 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +        description: WCA资料整理组是一个WCA的咨询委员会。这个团队的任务是协助并负责将WCA过去的资料作整理保存。
```suggestion
WCA资料整理组是一个WCA的咨询委员会。这个团队的任务是协助并负责将WCA过去的资料作整理保存。
```

2024-01-31 04:51 UTC, hanwu85 commented on WcaOnRails/config/locales/zh-CN.yml
> +      text: 世界魔方协会负责管理魔方的比赛，这些魔方是通过转动一部分块来操作，通常称为“魔方”（twisty puzzles)。
感觉上比现在的好

2024-01-31 04:53 UTC, hanwu85 commented
You can refer to this guideline for easier and faster translation for WCA website. 
https://docs.worldcubeassociation.org/guides/translating_the_website

2024-02-01 03:43 UTC, hanwu85 approved these changes
I think this is not a bad translation.
No translation is perfect, but I think it is good enough.
@notrichardpeng would be appreciated if you could give your input as well.

2024-02-05 01:15 UTC, notrichardpeng commented
LGTM, sorry for the delay, and thanks for your additional input @hanwu85

2024-02-05 01:18 UTC, notrichardpeng approved these changes

2024-02-05 09:41 UTC, merged