Add webmock for request stubbing during tests
thewca/worldcubeassociation.org pull request #8944
Opened 2024-02-26 05:46 UTC by dunkOnIT

This will be used in #8927, but introducing it as a separate PR given that its out of scope for that PR.

2024-03-04 12:33 UTC, gregorbg requested changes
Please add an evnrionment config (in the `.env` files) that allows you to enable/disable webmock by setting the corresponding env var to true/false (and have the spec config files pick up the env variable accordingly)

I also think that the default should be to disable webmock. and let developers choose locally whether they would like to enable it for local testing. The reasonable default should be to make live calls wherever and whenever possible

2024-03-05 06:06 UTC, dunkOnIT commented
Added env variables for the following:
* enabling/disabling HTTP connections
* enabling/disabling webmock stubs (not used in this PR, but will be incorporated into the Paypal PR)

2024-03-05 11:36 UTC, gregorbg commented
You famously missed an `end` in your latest ommit. The tests cannot even start to run because of syntax errors.

2024-03-05 12:07 UTC, gregorbg approved these changes

2024-03-05 12:08 UTC, gregorbg requested changes

2024-03-05 12:08 UTC, gregorbg commented on env_config.rb
> +    optional :ENABLE_NET_CONNECT_IN_TESTS, :bool, true
Here you declared it as `ENABLE` but below in the actual config you're using `DISABLE`

2024-03-05 12:08 UTC, gregorbg commented on spec/rails_helper.rb
> +    WebMock.allow_net_connect! unless EnvConfig.DISABLE_NET_CONNECT_IN_TESTS?
ENABLE vs DISABLE, see above.

2024-03-06 11:29 UTC, gregorbg approved these changes

2024-03-06 11:56 UTC, merged