Remove Deprecated Delegate edit page
thewca/worldcubeassociation.org pull request #9103
Opened 2024-03-23 03:39 UTC by danieljames-dj

This PR is ready for review. But needs to be informed to Senior Delegate before merged. I'll undraft this PR once I inform Senior Delegate. (Only blocker for informing Senior Delegate is https://github.com/thewca/worldcubeassociation.org/pull/9095)

2024-03-25 17:44 UTC, gregorbg requested changes

2024-03-25 17:44 UTC, gregorbg commented on spec/controllers/api/v0/user_roles_controller_spec.rb
As always, I am very unhappy about tests being removed :(
Why did you decide to do this and why are these tests not necessary anymore?

2024-03-25 17:53 UTC, danieljames-dj commented on spec/controllers/api/v0/user_roles_controller_spec.rb
Reason why these tests are removed is the corresponding code is also removed. There are no tests for the new flow of the actions because the action methods are currently bit complicated. Once the migration is completed, it will be very easy to add the test cases I believe.

2024-03-25 17:54 UTC, danieljames-dj commented on spec/controllers/api/v0/user_roles_controller_spec.rb
PS: The 'new flow' I mentioned here is not added in this PR, it was already there. This PR is just removing some of the existing code which is no longer used.

2024-03-25 18:07 UTC, gregorbg approved these changes

2024-03-29 20:10 UTC, gregorbg approved these changes
FOrmally approved, feel free to merge this after March 31 at your own discretion

2024-04-01 02:36 UTC, merged