Update zh-cn.yml and zh-TW.yml.
thewca/worldcubeassociation.org pull request #9135
Opened 2024-03-31 07:45 UTC by 2016WUJI01

2024-04-02 14:30 UTC, hanwu85 commented
> Also, what is the context of the change in zh-TW?

It is a single Chinese character fix.  But actually in TW chinese, it is the correct one.  Therefore, no need to fix it.

2024-04-03 07:43 UTC, 2016WUJI01 commented
Sorry for change zh-TW.
This pr changed this page: https://www.worldcubeassociation.org/teams-committees-councils

2024-04-04 08:29 UTC, gregorbg requested changes

2024-04-04 08:29 UTC, gregorbg commented on config/locales/zh-TW.yml
> +        WCA的團隊和委員會是整個組織的一部分並負責日常的事務才能讓整個組織運作。這些團隊是由WCA成員包含WCA代表和參賽者所組成的。每一個團隊會都有一個領導者，他們的職務是確保整個團隊的正常運作以及帶領其他團隊成員。理事會是一個特殊的團隊，他們的工作是擔任WCA董事會諮詢的角色，由社群成員組成而非WCA員工。當有委員會、團隊、理事會的空缺時，如何申請的資訊將會公布在首頁。
Please undo this change as per the previous discussion.

2024-04-05 05:22 UTC, 2016WUJI01 commented
> In that case, please undo the change in `zh-TW.yml`.
> 
> Also, I would really prefer if you could get _any_ Chinese Delegate to approve you as a translator. That way, we don't have to discuss and get reviews under every single individual PR. Is there any chance that you can get any Chinese Delegate to confirm you?

I can't find any Chinese Delegate to vouch for me as a translator. Might need @notrichardpeng for future PRs.

2024-04-09 03:33 UTC, notrichardpeng commented
> > In that case, please undo the change in `zh-TW.yml`.
> > Also, I would really prefer if you could get _any_ Chinese Delegate to approve you as a translator. That way, we don't have to discuss and get reviews under every single individual PR. Is there any chance that you can get any Chinese Delegate to confirm you?
> 
> I can't find any Chinese Delegate to vouch for me as a translator. Might need @notrichardpeng for future PRs.

I don't mind reviewing translations, but have you reached out to any of them?

2024-04-09 03:41 UTC, 2016WUJI01 commented
> reached



> > > In that case, please undo the change in `zh-TW.yml`.
> > > Also, I would really prefer if you could get _any_ Chinese Delegate to approve you as a translator. That way, we don't have to discuss and get reviews under every single individual PR. Is there any chance that you can get any Chinese Delegate to confirm you?
> > 
> > 
> > I can't find any Chinese Delegate to vouch for me as a translator. Might need @notrichardpeng for future PRs.
> 
> I don't mind reviewing translations, but have you reached out to any of them?

Yep, I tried to contact one of them @Baiqiang , but there was no reply.

2024-04-09 03:45 UTC, notrichardpeng requested changes

2024-04-09 03:45 UTC, notrichardpeng commented on config/locales/zh-CN.yml
> +        wsot: WCA竞技组织团队
既然是负责奥林匹克，"体育组织" 会不会好一点

2024-04-09 03:45 UTC, notrichardpeng commented on config/locales/zh-CN.yml
> +        WCA的团队和委员会是组织不可分割的一部分，执行保持其运作所需的日常任务。这些委员会由WCA社区成员组成，包括WCA代表和竞争对手。每个团队都有一个领导者，其作用是确保团队的正常运作并指导其他团队成员。理事会是一种特殊类型的团队，为WCA董事会发挥咨询作用，由社区成员组成，而不是WCA工作人员。当有委员会、团队或理事会空缺时，有关如何申请的信息会发布在首页上。
"竞争对手" 换成 “参赛人员” 应该更好一些

2024-04-09 03:45 UTC, notrichardpeng commented on config/locales/zh-CN.yml
> +        wsot: 该团队负责监督和协助WCA成为一个国际认可的竞技组织。
同上，“体育组织”？

2024-04-09 03:46 UTC, notrichardpeng commented
> > reached
> 
> > > > In that case, please undo the change in `zh-TW.yml`.
> > > > Also, I would really prefer if you could get _any_ Chinese Delegate to approve you as a translator. That way, we don't have to discuss and get reviews under every single individual PR. Is there any chance that you can get any Chinese Delegate to confirm you?
> > > 
> > > 
> > > I can't find any Chinese Delegate to vouch for me as a translator. Might need @notrichardpeng for future PRs.
> > 
> > 
> > I don't mind reviewing translations, but have you reached out to any of them?
> 
> Yep, I tried to contact one of them @Baiqiang , but there was no reply.

Perhaps look on WCA and see which delegates from China are actively organizing, they might have a better chance of responding.

2024-04-15 21:32 UTC, notrichardpeng approved these changes

2024-04-15 21:33 UTC, merged