Sort competitors by registration if no payment has been made in V2
thewca/worldcubeassociation.org pull request #9415
Opened 2024-05-24 13:06 UTC by FinnIckler

2024-05-25 06:12 UTC, gregorbg requested changes

2024-05-25 06:12 UTC, gregorbg commented on app/webpacker/components/RegistrationsV2/RegistrationAdministration/RegistrationAdministrationList.jsx
> +              return a.payment.updated_at.localeCompare(b.payment.updated_at);
Not a fan of comparing dates as strings. If this is currently working as intended, then probably it's only a "happy accident".

You should parse these timestamps into either JS-native `Date` or Luxon `DateTime` representation and then use those to compare

2024-05-25 06:12 UTC, gregorbg commented on app/webpacker/components/RegistrationsV2/RegistrationAdministration/RegistrationAdministrationList.jsx
> +            return a.competing.registered_on.localeCompare(
See above.

2024-05-27 19:35 UTC, FinnIckler commented on app/webpacker/components/RegistrationsV2/RegistrationAdministration/index.jsx
> +        </div>
it didn't, but it was throwing errors in the console making it harder to debug the issue. I could remove it from the diff and include it in another PR

2024-05-28 08:42 UTC, gregorbg commented on app/webpacker/components/RegistrationsV2/RegistrationAdministration/index.jsx
> +        </div>
Okay, nevermind then :D You can keep it in, my previous approval still holds

2024-05-30 14:55 UTC, merged