Redirect to users to contact form when allow_registration_edits is false and prefill it
thewca/worldcubeassociation.org pull request #9733
Opened 2024-08-01 14:40 UTC by FinnIckler

Gets rid of another of those pesky banners and allows users to contact the organizers with a prefilled template.

@danieljames-dj I know you worked on the contact form, is this the way I should interact with it to prefill it? I noticed you had the message property already there, but you wasn't using it

2024-08-01 15:01 UTC, danieljames-dj approved these changes
Hi @FinnIckler, yes the usages of the contact form looks good to me, I didn't had it in the reducer.js just because there wasn't any use-case so far and now you have.
I have also went through all the changes in this PR and overall LGTM, hence approved.

2024-08-06 04:43 UTC, dunkOnIT commented
@thewca-bot deploy staging

2024-08-27 14:51 UTC, dunkOnIT commented
@thewca-bot deploy staging

2024-08-30 05:15 UTC, dunkOnIT commented
@thewca-bot deploy staging

2024-08-31 02:23 UTC, dunkOnIT commented
@thewca-bot deploy staging

2024-08-31 05:39 UTC, dunkOnIT commented
The text formatting in the prefill could be a lot cleaner. I'd suggest the following format: 

> I would like to update my registration details as follows:
> Events: 3x3x3, 3bld
> Comment: Here's an example comment
> Guests: 7

And keep the behaviour of not including unchanged fields, that's great - eg if no change to guests is made: 

> I would like to update my registration details as follows:
> Events: 3x3x3, 3bld
> Comment: Here's an example comment

2024-08-31 05:45 UTC, dunkOnIT requested changes
Disregard the lines I added these comments on :P

2024-08-31 05:45 UTC, dunkOnIT commented on app/webpacker/components/RegistrationsV2/Register/CompetingStep.jsx
> +        const updateMessage = `${hasCommentChanged ? `Comment to ${comment} ` : ''}${hasEventsChanged ? `Events to ${selectedEvents.map((eventId) => events.byId[eventId].name).join(', ')} ` : ''}${ha
The text formatting in the prefill could be a lot cleaner. I'd suggest the following 

> I would like to update my registration details as follows:
> Events: 3x3x3, 3bld
> Comment: Here's an example comment
> Guests: 7


And keep the behaviour of not including unchanged fields, that's great - eg if no change to guests is made:

> I would like to update my registration details as follows:
> Events: 3x3x3, 3bld
> Comment: Here's an example comment

2024-08-31 05:45 UTC, dunkOnIT commented on app/webpacker/components/RegistrationsV2/Register/CompetingStep.jsx
> +        window.location = contactCompetitionUrl(competitionInfo.id, encodeURIComponent(i18n.t('competitions.registration_v2.update.update_contact_message', { update_params: updateMessage })));
Let's also add a banner message on the contact page which says the following: 

> To update your registration, you need to contact the organizers of the competition. We have prefilled the contact form with your requested changes - please submit the form.

2024-10-21 12:07 UTC, dunkOnIT approved these changes
Happy with the changes!

2024-11-26 05:56 UTC, merged