Allow certain Competition Form fields to be edited after announcement
thewca/worldcubeassociation.org pull request #9770
Opened 2024-08-13 09:36 UTC by gregorbg

Basically works as intended per the field list WCAT sent to us.

In the backend, we have to give "normal" users (i.e. Delegates, Organizers) permissions to make these edits across the board. There is no (easy) way to restrict edits to only certain fields in the backend. Let's see which tests explode because of this assumption.

If anyone has any smart suggestions about the `overrideEnabled` name, I'm all ears.

2024-08-15 14:54 UTC, FinnIckler commented on app/webpacker/components/CompetitionForm/FormSections/RegistrationDates.js
> +  }, []);
Add openingDateTime to dependency array

2024-08-26 01:36 UTC, kr-matthews commented
> If anyone has any smart suggestions about the `overrideEnabled` name, I'm all ears.

I'm not convinced that any of these are better, but how about `forceEnabled`, `forceAllowEdits`, or `ignoreDisabled`?

2024-09-17 13:14 UTC, FinnIckler commented
@thewca-bot deploy staging

2024-09-17 13:41 UTC, gregorbg commented
@thewca-bot deploy staging

2024-10-04 08:33 UTC, gregorbg commented
@thewca-bot deploy staging

2024-10-09 06:52 UTC, dunkOnIT commented
@thewca-bot deploy staging

2024-10-09 06:53 UTC, dunkOnIT commented
Merged main in and redeploying because I want to check/announce the Registration countdown timer on staging

2024-10-09 06:53 UTC, gregorbg commented
During your merge you pulled in a local Gemfile that has processor-specific hard dependencies installed. We need to revert that :P

2024-10-09 06:54 UTC, dunkOnIT commented
*cry*

2024-10-09 07:17 UTC, dunkOnIT commented
@thewca-bot deploy staging

2024-10-14 03:01 UTC, gregorbg commented
@thewca-bot deploy staging

2024-10-17 12:00 UTC, gregorbg commented
@thewca-bot deploy staging

2024-12-02 13:00 UTC, gregorbg commented
Testing. Right now (45 minutes ago from this comment) staging has been freshly deployed with a WRT PR to try and test, so we cannot deploy this at the same time

2025-04-04 08:37 UTC, gregorbg commented
@thewca-bot deploy staging

2025-04-07 13:38 UTC, gregorbg commented
@thewca-bot deploy staging

2025-04-09 07:54 UTC, dunkOnIT requested changes
Some nits/questions, plus editing for Registration Close seems to not be working.

Besides that, functionality of the form looks good!

2025-04-09 07:54 UTC, dunkOnIT commented on app/webpacker/components/CompetitionForm/Edit.js
> +  const allowsDisabledOverride = useMemo(() => {
Suggestion: `allowIgnoreDisabled`

2025-04-09 07:54 UTC, dunkOnIT commented on app/webpacker/components/CompetitionForm/FormSections/RegistrationFees.js
> +        <InputCurrencyAmount id="onTheSpotEntryFee" currency={currency} required={canRegOnSite} ignoreDisabled />
Should this be `ignoreDisabled` per WCAT's spec?

2025-04-09 07:54 UTC, dunkOnIT commented on app/webpacker/components/CompetitionForm/FormSections/RegistrationDates.js
> +          ignoreDisabled={registrationNotYetPast}
Running locally on WashtenawFMC22025, the Registration Close date remains un-editable: 
![image](https://github.com/user-attachments/assets/02a21d3c-add8-44b3-b7e5-7482d1a0a7d3)

2025-04-15 07:57 UTC, gregorbg commented on app/models/competition.rb
> +            "receiveRegistrationEmails" => { "type" => "boolean" },
No, good catch! This was a very old way of doing things, we have since extracted it to a separate component but forgot updating the reference here.

2025-04-15 07:57 UTC, gregorbg commented on app/models/competition.rb
> +  def self.delegate_edits_json_schema
You must have missed it -- it's directly at the top of the list under `properties`, called `"information"`

2025-04-15 07:57 UTC, gregorbg commented on app/models/competition.rb
> +        "information" => { "type" => ["string", "null"] },
(regarding my other comment: Here it is!)

2025-04-15 07:57 UTC, gregorbg commented on app/models/competition.rb
> +            "onTheSpotEntryFee" => { "type" => ["integer", "null"] },
The latter is correct, that's why it needs to be included in the spec.

The validations that you're suggesting would make sense in a follow-up PR. We would need to determine/establish what the actual "business logic relation" between OTS fee and registration fee is in that case.

2025-04-15 07:57 UTC, gregorbg commented on app/webpacker/components/CompetitionForm/FormSections/RegistrationFees.js
> +        <InputCurrencyAmount id="onTheSpotEntryFee" currency={currency} required={canRegOnSite} ignoreDisabled />
It has to be. Turning OTS on/off doesn't make sense without being able to edit the fee.

2025-04-15 07:57 UTC, gregorbg commented on app/webpacker/components/CompetitionForm/FormSections/RegistrationDates.js
> +          ignoreDisabled={registrationNotYetPast}
Fixed!

2025-04-16 02:46 UTC, merged