Gear order form in WCA website
thewca/worldcubeassociation.org pull request #9815
Opened 2024-08-26 02:08 UTC by danieljames-dj

In this PR, the gear order form is brought within WCA website so that there will be more options of customizations - for example, the notification emails can be well formatted in a way that it will reduce the workload of WFC, the user can know the total order value while filling the form, etc.

2024-08-26 02:11 UTC, danieljames-dj commented
This form is not 100% complete, currently I'm facing a blocker that if I mark any of the `Form.Input` as `required`, it will become 'red' even before user starts inputting any details. The same issue is happening with competition form as well if I give required.

I remember seeing this while working on Sign Up page migration, but iirc I couldn't find a solution during that time.

I request somebody to unblock this issue. Alternative is to use custom validation to check if all the fields are there.

2024-08-26 05:00 UTC, dunkOnIT commented
> it will become 'red' even before user starts inputting any details

Currently there is no workaround for this issue - that's how the form behaves in [v2 Register](https://staging.worldcubeassociation.org/competitions/CiuLaManchaOpen2024/register) as well. I think for now, proceed as if this were not a blocker.

2024-08-26 23:39 UTC, kr-matthews requested changes

2024-08-26 23:39 UTC, kr-matthews commented on app/webpacker/components/ContactGearOrderPage/index.jsx
> +  const equipments = [
"Equipment" doesn't have a plural form.
And this array could be moved out of the component.
```suggestion
  const equipment = [
```

2024-08-26 23:39 UTC, kr-matthews commented on app/webpacker/components/ContactGearOrderPage/GearOrderForm.jsx
> +  const [totalPrice, setTotalPrice] = useState(0);
Does this work? Direct calculation is better than a state and an effect.
```suggestion
  const totalPrice = _.sumBy(orderDetails, 'price');
```

2025-06-08 15:25 UTC, danieljames-dj commented
I'm closing this for now. WFC is currently relying on the spreadsheet, will check if bringing this to website will improve the process rapidly. If yes, will restart it.

2025-06-08 15:25 UTC, closed without merging